const constants = {
  DEMO_CONSTANT: "demo:get-demo-data",
  SEARCH_USERS: "data:search-users",
  SET_USER_ID: "data:set-user-id",
  CHART_CONSTANT: "data:get-chart-data",
  DETAILCARD_CONSTANT: "data:get-userdetail-data",
  GET_DASHBOARD_DATA: "data:get-dashboard-data",
  GET_SEARCH_QUERY: "data:search-query",
  TOGGLE_LOADING: "data:toggle-loading",
  LOGIN_USER: "user:login-user",
  LOGOUT_USER: "user:logout-user",
  GET_FOLLOWERS: "data:get-followers",
  GET_TENDENCIES: "data:get-tendencies-data",
  TOGGLE_MODAL: "user:toggle-modal",
  SET_MODAL_VIEW: "user:set-modal-view",
  GET_NOTES: "user:get-notes",
  ADD_NOTE: "user:add-note",
  EDIT_NOTE: "user:edit-note",
  DELETE_NOTE: "user:delete-note",
  FOLLOW_USER: "data:follow_user",
  UNFOLLOW_USER: "data:unfollow_user",
  TRIGGER_NOTES_SEARCH: "search:trigger-search-notes",
  SET_NOTES_SEARCH: "search:set-search-notes",
  FILTER_NOTES: "search:filter-search-notes",
  BASE_URL_PROD: "https://git-user-breakdown.herokuapp.com",
  BASE_URL_DEV: "https://staging-master-5ton9t2hfmasnxc.herokuapp.com",
  BASE_URL_POST_PROD: "https://staging-master-5ton9t2hfmasnxc.herokuapp.com",
};

export default constants;
